### ISSUE TITLE
handling for API key (client_id/client_secret)

### ISSUE THREAD

**Issue by pjpritch** [pratyushmittal/fetch-on-rest#3]
the Rest() constructor should allow for adding a key that is appended to the URL or added as a custom header

**Comment by pratyushmittal** [comment]
Adding key as a default query parameter or including in body is supported.

[Tests and example for adding key as a query parameter.](https://github.com/pratyushmittal/fetch-on-rest/blob/4320bb285750b56f553ce7a881cb531430d55bc1/src/__tests__/rest-tests.js#L17-L24)

[Tests and example for including key or authorization headers in body.](https://github.com/pratyushmittal/fetch-on-rest/blob/4320bb285750b56f553ce7a881cb531430d55bc1/src/__tests__/rest-tests.js#L113-L120)

I hope this solves the purpose.
